# 데이터소스 관련 설정
spring:
  profiles:
    include: common
  jpa:
    simulation:
      properties:
        hibernate:
          format_sql: false
          show_sql: false
          use_sql_comments: false
          hbm2ddl:
            auto: update
          jdbc:
            batch_size: 1000
          order_updates: true
          order_inserts: true
    waternet:
      properties:
        hibernate:
          format_sql: false
          show_sql: false
          use_sql_comments: false
          dialect: org.hibernate.dialect.OracleDialect
          hbm2ddl:
            auto: none
          jdbc:
            batch_size: 1000
          order_updates: true
          order_inserts: true
  datasource:
    simulation:
      #개발서버
#      jdbc-url: jdbc:p6spy:postgresql://192.168.248.6:5432/postgres
#      username: postgres
#      password: postgres
      #오세진로컬
      jdbc-url: jdbc:p6spy:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      maximum-pool-size: 30
      minimum-idle: 2
      connection-timeout: 30000 #커넥션 풀 반환 대기시간
      validation-timeout: 5000 #커넥션 유효성검사 대기 시간
      idle-timeout: 600000 # 미사용 커넥션 유휴 대기 시간
      max-lifetime: 1800000 # connection pool 생존시간
      keepalive-time: 3000 # 커넥션확인 반복 시간
      initialization-fail-timeout: 1000  # 최초 연결 실패해도 앱은 실행 (중요)
    waternet:
      # 운영서버
#      jdbc-url: jdbc:tibero:thin:@172.20.244.70:8629:webwaternet
#      username: WATERNET
#      password: WATERNET
      #개발서버
      jdbc-url: jdbc:tibero:thin:@1.212.159.42:8629:tibero
      username: WATERNET_HA
      password: WATERNET_HA
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000 #커넥션 풀 반환 대기시간
      validation-timeout: 5000 #커넥션 유효성검사 대기 시간
      idle-timeout: 600000 # 미사용 커넥션 유휴 대기 시간
      max-lifetime: 1800000 # connection pool 생존시간
      keepalive-time: 3000 # 커넥션확인 반복 시간
      initialization-fail-timeout: -1  # 최초 연결 실패해도 앱은 실행 (중요)

# 아나콘다 관련
anaconda:
  home-path: C:/anaconda3
  activate-path: ${anaconda.home-path}/Scripts/activate.bat
  python-env-path: ${anaconda.home-path}/envs

# 파일서버 관련
fileserver:
  base-path: D:/simulation/fileserver/htdocs

server:
  port: 8081

api:
  url: http://localhost:8080